Repository mit-plv/fiat-crypto, pull requests merged in 2018-02, with the labels that each got.

#305 [Work in Progress] Experiment with Bounds Analysis based on lists
  src/Experiments/SimplyTypedArithmetic.v
Labels: LGTM (ready to be merged by author), awaiting-continuous-integration-check

#309 [experiments] Implement much of the bounds pipeline (no proofs)
  src/Experiments/SimplyTypedArithmetic.v
Labels: LGTM (ready to be merged by author), awaiting-author-action, includes-wishlist

#314 NumTheoryUtil: make coqprime dependencies explicit
  src/Util/NumTheoryUtil.v
Labels: awaiting-continuous-integration-check

#316 Change Implicit Arguments to Arguments in coqprime
  coqprime/Coqprime/Iterator.v
  coqprime/Coqprime/Permutation.v
  coqprime/Coqprime/UList.v
Labels: awaiting-continuous-integration-check
