Repository mit-plv/fiat-crypto, pull requests merged in 2018-07, with the labels that each got.

#382 Prefer relations of the form [eq ==> eq ==> ... ==> eq] in setoids
  src/Util/FixCoqMistakes.v
Labels: awaiting-continuous-integration-check, awaiting-reviewer-feedback

#383 Adapt to coq#7254
  src/Arithmetic/BarrettReduction/RidiculousFish.v
  src/Experiments/NewPipeline/Language.v
  src/Experiments/PartialEvaluationWithLetIn.v
  src/Util/GlobalSettings.v
Labels: awaiting-author-action

#384 More zutil
  _CoqProject
  src/Experiments/NewPipeline/Arithmetic.v
  src/Experiments/SimplyTypedArithmetic.v
  src/Util/ZUtil.v
  src/Util/ZUtil/Div.v
  src/Util/ZUtil/Le.v
Labels: awaiting-continuous-integration-check

#386 Allow printing more easily readable code in errors
  src/Experiments/NewPipeline/CStringification.v
Labels: awaiting-continuous-integration-check

#387 Make Z.div_mod_to_quot_rem stronger
  _CoqProject
  src/Arithmetic/BarrettReduction/Generalized.v
  src/Arithmetic/BarrettReduction/RidiculousFish.v
  src/Arithmetic/Saturated/MontgomeryAPI.v
  src/Experiments/NewPipeline/Arithmetic.v
  src/Experiments/NewPipeline/Toplevel1.v
  src/Experiments/SimplyTypedArithmetic.v
  src/LegacyArithmetic/Double/Proofs/Multiply.v
  src/LegacyArithmetic/Double/Proofs/RippleCarryAddSub.v
  src/Util/QUtil.v
  src/Util/ZUtil.v
  src/Util/ZUtil/AddGetCarry.v
  src/Util/ZUtil/CC.v
  src/Util/ZUtil/Div.v
  src/Util/ZUtil/Div/Bootstrap.v
  src/Util/ZUtil/Modulo.v
  src/Util/ZUtil/Modulo/Bootstrap.v
  src/Util/ZUtil/Tactics/DivModToQuotRem.v
  src/Util/ZUtil/Tactics/RewriteModSmall.v
  src/Util/ZUtil/ZSimplify/Autogenerated.v
Labels: awaiting-continuous-integration-check

#396 Allow reification of nat_rect (fun _ => _ -> _)
  src/Experiments/NewPipeline/AbstractInterpretation.v
  src/Experiments/NewPipeline/CStringification.v
  src/Experiments/NewPipeline/CompilersTestCases.v
  src/Experiments/NewPipeline/GENERATEDIdentifiersWithoutTypes.v
  src/Experiments/NewPipeline/Language.v
  src/Experiments/NewPipeline/Rewriter.v
Labels: awaiting-continuous-integration-check

#389 Allow building with an external coqprime
  Makefile
Labels: awaiting-continuous-integration-check
