Repository mit-plv/fiat-crypto, pull requests merged in 2018-04, with the labels that each got.

#329 [experiments] Uncurry in phoas
  src/Experiments/SimplyTypedArithmetic.v
Labels: awaiting-reviewer-feedback

#335 comprehensive loops framework with complete proof theory
  _CoqProject
  src/Curves/Montgomery/XZ.v
  src/Curves/Montgomery/XZProofs.v
  src/Experiments/Loops.v
  src/Util/ForLoop.v
  src/Util/ForLoop/Instances.v
  src/Util/ForLoop/InvariantFramework.v
  src/Util/ForLoop/Tests.v
  src/Util/ForLoop/Unrolling.v
  src/Util/Loop.v
  src/Util/Loops.v
Labels: awaiting-reviewer-feedback, includes-wishlist

#348 Error if a display target fails
  Makefile
Labels: awaiting-continuous-integration-check
