Repository mit-plv/fiat-crypto, pull requests merged in 2020-04, with the labels that each got.

#714 Update the multiret rewrite rules
  src/Rewriter/Rules.v
Labels: awaiting-continuous-integration-check

#731 Make the wbw-montgomery functions explicit
  Makefile
  fiat-c/src/p224_32.c
  fiat-c/src/p224_64.c
  fiat-c/src/p256_32.c
  fiat-c/src/p256_64.c
  fiat-c/src/p384_32.c
  fiat-c/src/p384_64.c
  fiat-c/src/p434_64.c
  fiat-c/src/secp256k1_32.c
  fiat-c/src/secp256k1_64.c
  fiat-go/src/p224_32.go
  fiat-go/src/p224_64.go
  fiat-go/src/p256_32.go
  fiat-go/src/p256_64.go
  fiat-go/src/p384_32.go
  fiat-go/src/p384_64.go
  fiat-go/src/p434_64.go
  fiat-go/src/secp256k1_32.go
  fiat-go/src/secp256k1_64.go
  fiat-rust/src/p224_32.rs
  fiat-rust/src/p224_64.rs
  fiat-rust/src/p256_32.rs
  fiat-rust/src/p256_64.rs
  fiat-rust/src/p384_32.rs
  fiat-rust/src/p384_64.rs
  fiat-rust/src/p434_64.rs
  fiat-rust/src/p448_solinas_64.rs
  fiat-rust/src/p521_64.rs
  fiat-rust/src/secp256k1_32.rs
  fiat-rust/src/secp256k1_64.rs
Labels: awaiting-continuous-integration-check

#724 Also run coqchk on the CI
  .github/workflows/coq-macos.yml
  .github/workflows/coq-windows.yml
  .github/workflows/coq.yml
  .gitignore
Labels: awaiting-reviewer-feedback

#742 [ci] [windows] Switch to V8.11.1
  .github/workflows/coq-windows.yml
Labels: awaiting-continuous-integration-check

#746 Don't run validate on PRs
  .github/workflows/coq-macos.yml
  .github/workflows/coq-windows.yml
  .github/workflows/coq.yml
Labels: awaiting-author-action, awaiting-continuous-integration-check

#723 Optimize adc that generates no carry into add
  fiat-c/src/p224_32.c
  fiat-c/src/p224_64.c
  fiat-c/src/p256_32.c
  fiat-c/src/p256_64.c
  fiat-c/src/p384_32.c
  fiat-c/src/p384_64.c
  fiat-c/src/p434_64.c
  fiat-c/src/secp256k1_32.c
  fiat-c/src/secp256k1_64.c
  fiat-go/src/p224_32.go
  fiat-go/src/p224_64.go
  fiat-go/src/p256_32.go
  fiat-go/src/p256_64.go
  fiat-go/src/p384_32.go
  fiat-go/src/p384_64.go
  fiat-go/src/p434_64.go
  fiat-go/src/secp256k1_32.go
  fiat-go/src/secp256k1_64.go
  fiat-java/src/FiatP224.java
  fiat-java/src/FiatP256.java
  fiat-java/src/FiatP384.java
  fiat-java/src/FiatSecp256K1.java
  fiat-rust/src/p224_32.rs
  fiat-rust/src/p224_64.rs
  fiat-rust/src/p256_32.rs
  fiat-rust/src/p256_64.rs
  fiat-rust/src/p384_32.rs
  fiat-rust/src/p384_64.rs
  fiat-rust/src/p434_64.rs
  fiat-rust/src/secp256k1_32.rs
  fiat-rust/src/secp256k1_64.rs
  src/BoundsPipeline.v
  src/Rewriter/Passes/ArithWithCasts.v
  src/Rewriter/Rules.v
  src/Rewriter/RulesProofs.v
Labels: awaiting-reviewer-feedback

#754 Give stringification access to machine_wordsize
  src/Bedrock/Stringification.v
  src/BoundsPipeline.v
  src/CLI.v
  src/PushButtonSynthesis/BarrettReduction.v
  src/PushButtonSynthesis/BaseConversion.v
  src/PushButtonSynthesis/FancyMontgomeryReduction.v
  src/PushButtonSynthesis/Primitives.v
  src/PushButtonSynthesis/SaturatedSolinas.v
  src/PushButtonSynthesis/SmallExamples.v
  src/PushButtonSynthesis/UnsaturatedSolinas.v
  src/PushButtonSynthesis/WordByWordMontgomery.v
  src/SlowPrimeSynthesisExamples.v
  src/Stringification/C.v
  src/Stringification/Go.v
  src/Stringification/Java.v
  src/Stringification/Language.v
  src/Stringification/Rust.v
Labels: awaiting-continuous-integration-check

#756 Deal with splitting 32x64 mul, not just 64x32 mul
  src/Rewriter/Rules.v
  src/Rewriter/RulesProofs.v
Labels: awaiting-continuous-integration-check

#758 Remove string cruft that's been upstreamed
  _CoqProject
  src/Bedrock/Defaults.v
  src/Bedrock/Stringification.v
  src/CLI.v
  src/PushButtonSynthesis/BaseConversion.v
  src/PushButtonSynthesis/Primitives.v
  src/PushButtonSynthesis/SaturatedSolinas.v
  src/PushButtonSynthesis/UnsaturatedSolinas.v
  src/PushButtonSynthesis/WordByWordMontgomery.v
  src/StandaloneHaskellMain.v
  src/StandaloneOCamlMain.v
  src/Stringification/C.v
  src/Stringification/Go.v
  src/Stringification/IR.v
  src/Stringification/Java.v
  src/Stringification/Language.v
  src/Stringification/Rust.v
  src/Util/Arg.v
  src/Util/Strings/Ascii.v
  src/Util/Strings/BinaryString.v
  src/Util/Strings/Decimal.v
  src/Util/Strings/Equality.v
  src/Util/Strings/HexString.v
  src/Util/Strings/OctalString.v
  src/Util/Strings/Parse/Common.v
  src/Util/Strings/ParseArithmetic.v
  src/Util/Strings/Show.v
  src/Util/Strings/String.v
Labels: awaiting-continuous-integration-check

#760 Instantiate correctness proofs for bedrock2 tests
  src/Bedrock/Tests/Proofs/X25519_32.v
  src/Bedrock/Tests/Proofs/X25519_64.v
  src/Bedrock/Tests/X25519_32.v
  src/Bedrock/Tests/X25519_64.v
Labels: awaiting-continuous-integration-check
